---
gerrit_account_name: gerrit
gerrit_account_comment: Gerrit User
gerrit_account_home: "{{ gerrit_install_dir }}"
gerrit_account_group: gerrit
gerrit_global_pass: $6$ORmN2r3j8$YIWsVOdiJzwYmbI0.d/n5ggM0K6R6voWeQaI97zeDqMPS2934D3FWp/YWHFxBsvcg0mdocMnL7Q/xsimxZjTA. #gerrit123 sha256 hashed

gerrit_auth_type: OPENID  #defines authorization type...OPENID, LDAP, LDAP_BIND...

gerrit_db_type: mysql
gerrit_db_name: reviewdb
gerrit_db_user: gerrit
gerrit_db_host: localhost

gerrit_dl_url: https://www.gerritcodereview.com/download
gerrit_dl_sha256sum: 8f2e2e61b939664a20a025ef4f99095c08be14342ea5457bf5613bccedabcd27

gerrit_http_listen_port: 8080
gerrit_init: "java -jar {{ gerrit_war_path }} init --batch --no-auto-start -d {{ gerrit_install_dir }} --install-plugin reviewnotes --install-plugin download-commands --install-plugin singleusergroup"
gerrit_war_dir: /opt/
gerrit_war_path: "{{ gerrit_war_dir }}/{{ gerrit_war_name }}"
gerrit_war_name: "gerrit-{{ gerrit_version }}.war"
gerrit_mysql_connector_file: mysql-connector-java-5.1.21.jar
gerrit_mysql_connector_url: http://repo2.maven.org/maven2/mysql/mysql-connector-java/5.1.21
gerrit_install_dir: /var/gerrit
gerrit_smtp_server: localhost
gerrit_sshd_listen_port: 29418
gerrit_version: 2.12

#MARIADB MYSQL

# defaults file for ansible-mariadb-mysql
mariadb_debian_repo: 'deb http://ftp.osuosl.org/pub/mariadb/repo/{{ mariadb_version }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} main'
mariadb_debian_repo_key: '0xcbcb082a1bb943db'
mariadb_debian_repo_keyserver: 'keyserver.ubuntu.com'
mariadb_redhat_repo: 'http://yum.mariadb.org/{{ mariadb_version }}/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version|int}}-amd64'
mariadb_redhat_repo_key: 'https://yum.mariadb.org/RPM-GPG-KEY-MariaDB'
mariadb_version: 10.0
mysql_allow_remote_connections: false  #defines if mysql should listen on loopback (default) or allow remove connections
mysql_port: 3306  #defines the port for mysql to listen on